# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0fcb881dcbf4001431fa53e3a9929274"
name = "MyOutfit"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "inventory_levels/update" ]
  uri = "/webhooks/inventory/update"

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/webhooks/products/create"

  [[webhooks.subscriptions]]
  topics = [ "products/delete" ]
  uri = "/webhooks/products/delete"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,read_orders"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[app_proxy]
url = "https://ac95d22206d7.ngrok-free.app"
subpath = "outfit-completer"
prefix = "apps"
